
package atm_proyect;

import static atm_proyect.ATM_PROYECT.CAJERO;

/**
 *
 * @author FZ
 */
public class BIENVENIDA_USER extends javax.swing.JPanel {

    /**
     * Creates new form BIENVENIDA_USER
     */
    public BIENVENIDA_USER() {
        initComponents();
        //Instanciar El Nombre
        this.LABEL_BIENVENIDO.setText(this.LABEL_BIENVENIDO.getText()+" "+CAJERO.getNombre()+" "+CAJERO.getApellido());
        this.LABEL_NMCUENTA.setText(this.LABEL_NMCUENTA.getText()+" "+CAJERO.getNM_Cuenta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABEL_BIENVENIDO = new javax.swing.JLabel();
        LABEL_NMCUENTA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LABEL_BIENVENIDO.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        LABEL_BIENVENIDO.setForeground(new java.awt.Color(0, 0, 0));
        LABEL_BIENVENIDO.setText("Bienvenido");
        add(LABEL_BIENVENIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 360, -1));

        LABEL_NMCUENTA.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        LABEL_NMCUENTA.setForeground(new java.awt.Color(0, 0, 0));
        LABEL_NMCUENTA.setText("Nm Cuenta:");
        add(LABEL_NMCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 360, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favicon.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/LOGO_PROYECTO.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 330, 280));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABEL_BIENVENIDO;
    private javax.swing.JLabel LABEL_NMCUENTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
