/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm_proyect;
import static atm_proyect.ATM_PROYECT.CAJERO;
import javax.swing.JOptionPane;

/**
 *
 * @author saul_
 */
public class DepositoEfectivo extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public DepositoEfectivo() {
        initComponents();
        this.INPUT_CUENTA.setText(CAJERO.getNM_Cuenta());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        INPUT_CUENTA = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        INPUT_MONTO = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 280, 18));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favicon.png"))); // NOI18N
        jLabel1.setText("DEPOSITO EFECTIVO A CUENTA PROPIA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 29, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NUMERO DE CUENTA");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 116, 260, -1));

        INPUT_CUENTA.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_CUENTA.setBorder(null);
        INPUT_CUENTA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        INPUT_CUENTA.setEnabled(false);
        add(INPUT_CUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 136, 274, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 156, 274, 18));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("MONTO A DEPOSITAR");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 260, -1));

        INPUT_MONTO.setBackground(new java.awt.Color(255, 255, 255));
        INPUT_MONTO.setBorder(null);
        INPUT_MONTO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0.00"))));
        INPUT_MONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_MONTOActionPerformed(evt);
            }
        });
        add(INPUT_MONTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/HOWIE.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Validacion Campo Vacio
        if (this.INPUT_MONTO.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "NO SE PERMITEN CAMPOS VACIOS", "ERROR NULL", HEIGHT);
            return;
        }

        //Variables Intermedias
        String Nm_DEPOSITO;
        double Cantidad_Deposito;
                
        //Obtencion de Datos
        Nm_DEPOSITO=this.INPUT_CUENTA.getText();
        Cantidad_Deposito=Double.parseDouble(INPUT_MONTO.getText());
        
        //Condicion de maximo ingreso
        if (Cantidad_Deposito>=50000.01) {
            JOptionPane.showMessageDialog(INPUT_MONTO, "CANTIDAD MAYOR AL LIMITE(50,000.01)", "TRANSACCION INVALIDA", HEIGHT);
            return;
        }        
        
        //Validacion de Montos Incorrectos
        if(Cantidad_Deposito<0){
        JOptionPane.showMessageDialog(INPUT_MONTO, "No se puede Procesar valores Negativos", "TRANFERENCIA INVALIDA", HEIGHT);
        return;
        }else if(Cantidad_Deposito==0){
        JOptionPane.showMessageDialog(INPUT_MONTO, "Ingrese una Cantidad Mayor", "TRANFERENCIA INVALIDA", HEIGHT);
        return;
        }
        
        //Proceso de Datos;
        CAJERO.DEPOSITOEFVO(Cantidad_Deposito, Nm_DEPOSITO);
        JOptionPane.showMessageDialog(INPUT_CUENTA, "Deposito Efectuado Correctamente", "TRANFERENCIA EXITOSA",HEIGHT );

        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void INPUT_MONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_MONTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INPUT_MONTOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField INPUT_CUENTA;
    private javax.swing.JFormattedTextField INPUT_MONTO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
