/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_proyect;


import static atm_proyect.ATM_PROYECT.CAJERO;
import static atm_proyect.ATM_PROYECT.LOGIN;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author FZ
 */
public class GUI_BANCO extends javax.swing.JFrame {

    /**
     * Creates new form GUI_BANCO
     */
    public GUI_BANCO() {
        initComponents();
        setLocationRelativeTo(null);
        BIENVENIDA_USER BIENVENIDA= new BIENVENIDA_USER();
        ShowPanel(BIENVENIDA);
        
    }
    private void ShowPanel(JPanel p){
        p.setSize(650, 410);
        p.setLocation(0, 0);
        CONTENT.removeAll();
        CONTENT.add(p,BorderLayout.CENTER);
        CONTENT.revalidate();
        CONTENT.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        PANEL_SUBMENUS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        LABEL_NMCUENTA = new javax.swing.JLabel();
        RETIRO_LABEL = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        DEPOSITAR_LABEL = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        TRANSFERIR_LABEL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        COSULTA_LABEL = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        LABEL_SALIR = new javax.swing.JLabel();
        COSULTA_LABEL1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        CONTENT = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANEL_SUBMENUS.setBackground(new java.awt.Color(0, 153, 255));
        PANEL_SUBMENUS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BANCO CEUTEC");
        PANEL_SUBMENUS.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PANEL_SUBMENUS.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 43, 170, 10));

        LABEL_NMCUENTA.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        LABEL_NMCUENTA.setForeground(new java.awt.Color(255, 255, 255));
        LABEL_NMCUENTA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABEL_NMCUENTA.setText("By EF&CF");
        PANEL_SUBMENUS.add(LABEL_NMCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, -1));

        RETIRO_LABEL.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        RETIRO_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        RETIRO_LABEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/retiro-de-efectivo.png"))); // NOI18N
        RETIRO_LABEL.setText("Retiro");
        RETIRO_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RETIRO_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RETIRO_LABELMouseClicked(evt);
            }
        });
        PANEL_SUBMENUS.add(RETIRO_LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PANEL_SUBMENUS.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 137, 170, -1));

        DEPOSITAR_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        DEPOSITAR_LABEL.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        DEPOSITAR_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        DEPOSITAR_LABEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/donacion.png"))); // NOI18N
        DEPOSITAR_LABEL.setText("Depositar");
        DEPOSITAR_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DEPOSITAR_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DEPOSITAR_LABELMouseClicked(evt);
            }
        });
        PANEL_SUBMENUS.add(DEPOSITAR_LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PANEL_SUBMENUS.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 170, 10));

        TRANSFERIR_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        TRANSFERIR_LABEL.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        TRANSFERIR_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        TRANSFERIR_LABEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/transferir.png"))); // NOI18N
        TRANSFERIR_LABEL.setText("Transferir");
        TRANSFERIR_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TRANSFERIR_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TRANSFERIR_LABELMouseClicked(evt);
            }
        });
        PANEL_SUBMENUS.add(TRANSFERIR_LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PANEL_SUBMENUS.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 10));

        COSULTA_LABEL.setBackground(new java.awt.Color(0, 0, 0));
        COSULTA_LABEL.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        COSULTA_LABEL.setForeground(new java.awt.Color(255, 255, 255));
        COSULTA_LABEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/refinanciar.png"))); // NOI18N
        COSULTA_LABEL.setText("Consultar Saldo");
        COSULTA_LABEL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        COSULTA_LABEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COSULTA_LABELMouseClicked(evt);
            }
        });
        PANEL_SUBMENUS.add(COSULTA_LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PANEL_SUBMENUS.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 170, 10));

        LABEL_SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cerrar-sesion_1.png"))); // NOI18N
        LABEL_SALIR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LABEL_SALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LABEL_SALIRMouseClicked(evt);
            }
        });
        PANEL_SUBMENUS.add(LABEL_SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 50, 40));

        COSULTA_LABEL1.setBackground(new java.awt.Color(0, 0, 0));
        COSULTA_LABEL1.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        COSULTA_LABEL1.setForeground(new java.awt.Color(255, 255, 255));
        COSULTA_LABEL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/historicoico.png"))); // NOI18N
        COSULTA_LABEL1.setText("Historial");
        COSULTA_LABEL1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        COSULTA_LABEL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                COSULTA_LABEL1MouseClicked(evt);
            }
        });
        PANEL_SUBMENUS.add(COSULTA_LABEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PANEL_SUBMENUS.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 170, 10));

        jPanel1.add(PANEL_SUBMENUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 410));

        CONTENT.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CONTENTLayout = new javax.swing.GroupLayout(CONTENT);
        CONTENT.setLayout(CONTENTLayout);
        CONTENTLayout.setHorizontalGroup(
            CONTENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        CONTENTLayout.setVerticalGroup(
            CONTENTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(CONTENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 650, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RETIRO_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RETIRO_LABELMouseClicked
        RETIRAR_DINERO R1 = new RETIRAR_DINERO();
        ShowPanel(R1);
    }//GEN-LAST:event_RETIRO_LABELMouseClicked

    private void TRANSFERIR_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TRANSFERIR_LABELMouseClicked
        Transferir R2 = new Transferir();
        ShowPanel(R2);
    }//GEN-LAST:event_TRANSFERIR_LABELMouseClicked

    private void DEPOSITAR_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DEPOSITAR_LABELMouseClicked
        DepositoEfectivo R3 = new DepositoEfectivo();
        ShowPanel(R3);
    }//GEN-LAST:event_DEPOSITAR_LABELMouseClicked

    private void LABEL_SALIRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LABEL_SALIRMouseClicked
        this.dispose();
        LOGIN.setVisible(true);
        CAJERO.setNM_Cuenta("");
        CAJERO.setPin_Cuenta("");
        CAJERO.setSaldo(0);
        
    }//GEN-LAST:event_LABEL_SALIRMouseClicked

    private void COSULTA_LABELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COSULTA_LABELMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Su saldo es:"+CAJERO.getSaldo(), "CONSULTA SALDO", HEIGHT);
        CAJERO.GUARDAR_TEXTO(4, String.valueOf(CAJERO.getSaldo()),"");
    }//GEN-LAST:event_COSULTA_LABELMouseClicked

    private void COSULTA_LABEL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_COSULTA_LABEL1MouseClicked
       HISTORIAL_ACCIONES R4 = new HISTORIAL_ACCIONES();
       ShowPanel(R4);
    }//GEN-LAST:event_COSULTA_LABEL1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_BANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_BANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_BANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_BANCO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_BANCO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONTENT;
    private javax.swing.JLabel COSULTA_LABEL;
    private javax.swing.JLabel COSULTA_LABEL1;
    private javax.swing.JLabel DEPOSITAR_LABEL;
    private javax.swing.JLabel LABEL_NMCUENTA;
    private javax.swing.JLabel LABEL_SALIR;
    private javax.swing.JPanel PANEL_SUBMENUS;
    private javax.swing.JLabel RETIRO_LABEL;
    private javax.swing.JLabel TRANSFERIR_LABEL;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
