/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm_proyect;

import static atm_proyect.ATM_PROYECT.CAJERO;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author FZ
 */
public class HISTORIAL_ACCIONES extends javax.swing.JPanel {

    /**
     * Creates new form HISTORIAL_ACCIONES
     */
    public HISTORIAL_ACCIONES() {
        initComponents();
        //INSTANCIAR AUTOMATICAMENTE
        
        //Obtener USUARIO
        String NmCuenta = CAJERO.getNM_Cuenta();
        
        //OBTENER DATOS DE BITACORA
        List<String> DATOS = CAJERO.leer_bitacora();
        
        //FILTRAR BITACORA
        List<String> FILTRO = CAJERO.filtrar_bitacora(DATOS, NmCuenta);
        
        //CREAR JLIST Y METER DATOS
        DefaultListModel<String> LISTA = new DefaultListModel<>();
        
        for (String DATO:FILTRO) {
            LISTA.addElement(DATO);
        }
        this.LISTA_HISTORIAL.setModel(LISTA);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LISTA_HISTORIAL = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        LISTA_HISTORIAL.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(LISTA_HISTORIAL);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favicon.png"))); // NOI18N
        jLabel1.setText("HISTORIAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LISTA_HISTORIAL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
