/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm_proyect;

import static atm_proyect.ATM_PROYECT.CAJERO;
import javax.swing.JOptionPane;

public class RETIRAR_DINERO extends javax.swing.JPanel {

    /**
     * Creates new form RETIRAR_DINERO
     */
    public RETIRAR_DINERO() {
        initComponents();
    }
    public void RETIRAR_PROCESO (double Cantidad){
        //Concatenar Metodos de Clases
       boolean acceso=CAJERO.verificacion_fondos(Cantidad);
        if (acceso==true) {
            CAJERO.Retirar(acceso, Cantidad);
            JOptionPane.showMessageDialog(jPanel2, "RETIRO REALIZADO CON EXITO", "RETIRO", HEIGHT);
        }else{
            JOptionPane.showMessageDialog(jPanel2, "FONDOS INSUFICIENTES", "RETIRO", HEIGHT);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN3 = new javax.swing.JButton();
        BTN1 = new javax.swing.JButton();
        BTN2 = new javax.swing.JButton();
        BTN4 = new javax.swing.JButton();
        BTN5 = new javax.swing.JButton();
        BTN6 = new javax.swing.JButton();
        BTN7 = new javax.swing.JButton();
        BTN8 = new javax.swing.JButton();
        BTN9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 410));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/favicon.png"))); // NOI18N
        jLabel1.setText("RETIRAR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, -1));

        BTN3.setBackground(new java.awt.Color(255, 255, 255));
        BTN3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN3.setForeground(new java.awt.Color(0, 0, 0));
        BTN3.setText("500");
        BTN3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN3ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 90, 90, 30));

        BTN1.setBackground(new java.awt.Color(255, 255, 255));
        BTN1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN1.setForeground(new java.awt.Color(0, 0, 0));
        BTN1.setText("100");
        BTN1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN1ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 90, 90, 30));

        BTN2.setBackground(new java.awt.Color(255, 255, 255));
        BTN2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN2.setForeground(new java.awt.Color(0, 0, 0));
        BTN2.setText("200");
        BTN2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN2ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 30));

        BTN4.setBackground(new java.awt.Color(255, 255, 255));
        BTN4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN4.setForeground(new java.awt.Color(0, 0, 0));
        BTN4.setText("1000");
        BTN4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN4ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 138, 90, 30));

        BTN5.setBackground(new java.awt.Color(255, 255, 255));
        BTN5.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN5.setForeground(new java.awt.Color(0, 0, 0));
        BTN5.setText("1500");
        BTN5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN5ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 138, 90, 30));

        BTN6.setBackground(new java.awt.Color(255, 255, 255));
        BTN6.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN6.setForeground(new java.awt.Color(0, 0, 0));
        BTN6.setText("2000");
        BTN6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN6ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 138, 90, 30));

        BTN7.setBackground(new java.awt.Color(255, 255, 255));
        BTN7.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN7.setForeground(new java.awt.Color(0, 0, 0));
        BTN7.setText("2500");
        BTN7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN7ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 186, 90, 30));

        BTN8.setBackground(new java.awt.Color(255, 255, 255));
        BTN8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN8.setForeground(new java.awt.Color(0, 0, 0));
        BTN8.setText("3000");
        BTN8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN8ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 186, 90, 30));

        BTN9.setBackground(new java.awt.Color(255, 255, 255));
        BTN9.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        BTN9.setForeground(new java.awt.Color(0, 0, 0));
        BTN9.setText("3500");
        BTN9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        BTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN9ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 186, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/HOWIE.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 260, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN3ActionPerformed
        String Cambio=this.BTN3.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN3ActionPerformed

    private void BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN1ActionPerformed

        String Cambio=this.BTN1.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);

    }//GEN-LAST:event_BTN1ActionPerformed

    private void BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN2ActionPerformed
        String Cambio=this.BTN2.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);

    }//GEN-LAST:event_BTN2ActionPerformed

    private void BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN4ActionPerformed
        String Cambio=this.BTN4.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN4ActionPerformed

    private void BTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN5ActionPerformed
        String Cambio=this.BTN5.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN5ActionPerformed

    private void BTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN6ActionPerformed
        String Cambio=this.BTN6.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN6ActionPerformed

    private void BTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN7ActionPerformed
        String Cambio=this.BTN7.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN7ActionPerformed

    private void BTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN8ActionPerformed
        String Cambio=this.BTN8.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN8ActionPerformed

    private void BTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN9ActionPerformed
        String Cambio=this.BTN9.getText();
        double Cantidad = Double.parseDouble(Cambio);
        RETIRAR_PROCESO(Cantidad);
    }//GEN-LAST:event_BTN9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN1;
    private javax.swing.JButton BTN2;
    private javax.swing.JButton BTN3;
    private javax.swing.JButton BTN4;
    private javax.swing.JButton BTN5;
    private javax.swing.JButton BTN6;
    private javax.swing.JButton BTN7;
    private javax.swing.JButton BTN8;
    private javax.swing.JButton BTN9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
